export const SHOW_BLOCKLIST_DATA = "SHOW_BLOCKLIST_DATA";
export const SHOW_WHITELIST_DATA = "SHOW_WHITELIST_DATA";
export const UPDATE_TFA_STATUS = "UPDATE_TFA_STATUS";
export const UPDATE_FARM_STATUS = "UPDATE_FARM_STATUS"
export const USER_INDEX = 'USER_INDEX';
export const ISWALLETCONNECTED = 'ISWALLETCONNECTED';
export const USER_ADDRESS = 'USER_ADDRESS';
export const BNB_BALANCE = 'BNB_BALANCE';
export const NATIVE_BALANCE = 'NATIVE_BALANCE';
export const BASEURL = 'BASEURL';
export const REFFERALADDRESS = 'REFFERALADDRESS';
export const TOTALFARMID = 'TOTALFARMID';
export const ENABLELOADER = 'ENABLELOADER';
export const LOADERTEXT = 'LOADERTEXT';
export const DOLLARVALUE = 'DOLLARVALUE';



export const UPDATE_GLOBAL_CHAIN_ID = 'UPDATE_GLOBAL_CHAIN_ID';